SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";


INSERT INTO features (id, title, slug, description, parent) VALUES ('126', 'Bathroom - Bath Tub', 'bathroom-bath-tub', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('193', 'Bathroom - Double Basin', 'bathroom-double-basin', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('195', 'Bathroom - Double Shower', 'bathroom-double-shower', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('125', 'Bathroom - Jacuzzi', 'bathroom-jacuzzi', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('197', 'Bathroom - Rain Shower', 'bathroom-rain-shower', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('196', 'Bathroom - Shaving Point', 'bathroom-shaving-point', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('194', 'Bathroom - Single Shower', 'bathroom-single-shower', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('116', 'Bedroom - Balcony', 'bedroom-balcony', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('156', 'Bedroom - Built In Wardrobe', 'bedroom-built-in-wardrobe', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('118', 'Bedroom - En-suite Bathroom/s', 'bedroom-en-suite-bathroom-s', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('198', 'Bedroom - King-size Bed', 'bedroom-king-size-bed', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('128', 'Bedroom - Large Balcony', 'bedroom-large-balcony', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('200', 'Bedroom - TV', 'bedroom-tv', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('199', 'Bedroom - Vanity Unit', 'bedroom-vanity-unit', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('182', 'Close To - Beach', 'close-to-beach', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('177', 'Close To - City Center', 'close-to-city-center', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('178', 'Close To - Golf Courses', 'close-to-golf-courses', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('179', 'Close To - International Hospitals', 'close-to-international-hospitals', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('180', 'Close To - International Schools', 'close-to-international-schools', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('181', 'Close To - Main Shopping Centers', 'close-to-main-shopping-centers', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('228', 'Condo Feature - 24 Hour Reception', 'condo-feature-24-hour-reception', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('225', 'Condo Feature - Club House & Bar', 'condo-feature-club-house-bar', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('131', 'Condo Feature - Communal Gardens', 'condo-feature-communal-gardens', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('162', 'Condo Feature - Communal Gym', 'condo-feature-communal-gym', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('46', 'Condo Feature - Communal Laundry', 'condo-feature-communal-laundry', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('82', 'Condo Feature - Communal Swimming Pool', 'condo-feature-swimming-pool', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('232', 'Condo Feature - Elevator-Lift', 'condo-feature-elevator-lift', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('112', 'Condo feature - High Floor', 'condo-high-floor', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('224', 'Condo Feature - Kid\'s Club', 'condo-feature-kids-club', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('229', 'Condo Feature - Laundry service', 'condo-feature-laundry-service', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('230', 'Condo Feature - Rooftop Garden', 'condo-feature-rooftop-garden', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('231', 'Condo Feature - Rooftop Pool', 'condo-feature-rooftop-pool', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('223', 'Condo Feature - Sun Deck', 'condo-feature-sun-deck', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('227', 'Condo Feature - Valet Parking', 'condo-feature-valet-parking', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('165', 'Condo Feature Communal 24 Hour Security', 'condo-feature-communal-24-hour-security', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('166', 'Condo Feature Communal Covered Parking', 'condo-feature-communal-covered-parking', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('167', 'Condo Feature Communal Jacuzzi Sauna', 'condo-feature-communal-jacuzzi-sauna', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('168', 'Condo Feature Communal Multi-Storey Parking', 'condo-feature-communal-multi-storey-parking', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('163', 'Condo Feature Communal Off Road Parking', 'condo-feature-communal-off-road-parking', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('164', 'Condo Feature Communal Restaurant', 'condo-feature-communal-restaurant', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('169', 'Condo Feature Communal Tennis Courts', 'condo-feature-communal-tennis-courts', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('14', 'Garden Feature - Barbeque Area', 'garden-feature-barbeque-area', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('153', 'Garden Feature - Garden Furniture', 'garden-feature-garden-furniture', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('107', 'Garden Feature - Landscaped Garden', 'garden-feature-landscaped-garden', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('129', 'Garden Feature - Large Terrace Area', 'garden-feature-large-terrace-area', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('47', 'Garden Feature - Lawn Area', 'garden-feature-lawn-area', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('71', 'Garden Feature - Outdoor Shower', 'garden-feature-outdoor-shower', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('138', 'Garden Feature - Private Garden', 'garden-feature-private-garden', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('157', 'Garden Feature - Sala House', 'garden-feature-sala-house', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('142', 'Garden Feature - Terrace Area', 'garden-feature-terrace-area', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('12', 'House Feature - Air Conditioning', 'house-feature-air-conditioning', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('150', 'House Feature - Breakfast Area', 'house-feature-breakfast-area', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('151', 'House Feature - Ceiling Fans', 'house-feature-ceiling-fans', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('154', 'House Feature - Dining Area', 'house-feature-dining-area', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('119', 'House Feature - Entertainment Room', 'house-feature-entertainment-room', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('121', 'House Feature - Fully Furnished', 'house-feature-fully-furnished', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('37', 'House Feature - Gym', 'house-feature-gym', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('152', 'House Feature - High Ceilings', 'house-feature-high-ceilings', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('148', 'House Feature - Hot & Cold Water', 'house-feature-hot-cold-water', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('147', 'House Feature - Internet', 'house-feature-internet', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('134', 'House Feature - Office/Study', 'house-feature-office-study', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('155', 'House Feature - Open Plan Lounge', 'house-feature-open-plan-lounge', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('122', 'House Feature - Part Furnished', 'house-feature-part-furnished', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('140', 'House Feature - Reserve Water Tank/s', 'house-feature-reserve-water-tank-s', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('79', 'House Feature - Sauna', 'house-feature-sauna', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('141', 'House Feature - Storage Room', 'house-feature-storage-room', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('143', 'House Feature - Thai Style Kitchen', 'house-feature-thai-style-kitchen', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('87', 'House Feature - TV Cable', 'house-feature-tv-cable', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('146', 'House Feature - TV Satellite', 'house-feature-tv-satellite', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('123', 'House Feature - Unfurnished', 'house-feature-unfurnished', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('92', 'House Feature - WiFi', 'house-feature-wifi', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('135', 'Kitchen - Cold Store', 'kitchen-cold-store', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('187', 'Kitchen - Cooking Utensils', 'kitchen-cooking-utensils', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('192', 'Kitchen - Dishwasher', 'kitchen-dishwasher', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('188', 'Kitchen - Double Door Fridge', 'kitchen-double-door-fridge', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('189', 'Kitchen - Double Sink', 'kitchen-double-sink', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('190', 'Kitchen - Electric Hob', 'kitchen-electric-hob', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('120', 'Kitchen - European Kitchen', 'kitchen-european-kitchen', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('242', 'Kitchen - Fridge Freezer', 'kitchen-fridge-freezer', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('191', 'Kitchen - Gas Hob', 'kitchen-gas-hob', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('127', 'Kitchen - Kitchenette', 'kitchen-kitchenette', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('186', 'Kitchen - Microwave', 'kitchen-microwave', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('185', 'Kitchen - Oven', 'kitchen-oven', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('158', 'Kitchen - Thai Style Kitchen', 'kitchen-thai-style-kitchen', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('90', 'Kitchen - Washing Machine', 'kitchen-washing-machine', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('226', 'Lobby- Lounge Area', 'lobby-lounge-area', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('205', 'Lounge - Bar Area', 'lounge-bar-area', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('203', 'Lounge - Built-in TV Cabinet', 'lounge-built-in-tv-cabinet', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('204', 'Lounge - Coffee Table', 'lounge-coffee-table', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('201', 'Lounge - Large Sofa', 'lounge-large-sofa', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('208', 'Lounge - Open Plan', 'lounge-open-plan', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('206', 'Lounge - Pool Table', 'lounge-pool-table', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('202', 'Lounge - Small Sofa', 'lounge-small-sofa', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('239', 'Ownership - Foreign Name', 'ownership-foreign-name', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('240', 'Ownership - N/A', 'ownership-n-a', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('238', 'Ownership - Thai Company Name', 'ownership-thai-company-name', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('237', 'Ownership - Thai Name', 'ownership-thai-name', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('212', 'Property Feature - Communal Park', 'property-feature-communal-park', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('210', 'Property Feature - Communal Pool', 'property-feature-communal-pool', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('109', 'Property Feature - Corner Unit', 'property-feature-corner-unit', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('117', 'Property Feature - Covered Parking', 'property-feature-covered-parking', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('110', 'Property Feature - Duplex', 'property-feature-duplex', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('111', 'Property Feature - Duplex Penthouse', 'property-feature-duplex-penthouse', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('211', 'Property Feature - Fitness Centre', 'property-feature-fitness-centre', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('124', 'Property Feature - Guest Accommodation', 'property-feature-guest-accommodation', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('130', 'Property Feature - Laundry Room', 'property-feature-laundry-room', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('132', 'Property Feature - Maids Quarters', 'property-feature-maids-quarters', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('133', 'Property Feature - Off-Road Parking', 'property-feature-off-road-parking', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('113', 'Property Feature - Penthouse', 'property-feature-penthouse', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('136', 'Property Feature - Personal Security System', 'property-feature-security-personal-security-system', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('114', 'Property Feature - Pool View', 'property-feature-pool-view', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('139', 'Property Feature - Private Swimming Pool', 'property-feature-private-swimming-pool', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('115', 'Property Feature - Sea View', 'property-feature-sea-view', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('137', 'Property Feature - Security - Gated', 'property-feature-security-gated', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('149', 'Property Feature - Security 24 hour Guard', 'property-feature-security-24-hour-guard', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('144', 'Property Feature - Water Pumps', 'property-feature-water-pumps', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('145', 'Property Feature - Water Well', 'property-feature-water-well', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('93', 'Property Feature - Window Security', 'property-feature-window-security', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('170', 'View - City Center View', 'view-city-center-view', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('171', 'View - Island View', 'view-island-view', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('172', 'View - Mountain View', 'view-mountain-view', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('173', 'View - Panoramic View', 'view-panoramic-view', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('174', 'View - Pool View', 'view-pool-view', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('175', 'View - Rural View', 'view-rural-view', '', '0');
INSERT INTO features (id, title, slug, description, parent) VALUES ('176', 'View - Sea View', 'view-sea-view', '', '0');


SET FOREIGN_KEY_CHECKS=1;
